name: Build and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tar: ${{ steps.save-image.outputs.image-tar }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: docker build -t ipa101 .

      - name: Save Docker image as tar
        id: save-image
        run: docker save ipa101:latest -o ipa101.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipa101-tar
          path: ipa101.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: ipa101-tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ipa101.tar
          target: /home/${{ secrets.EC2_USER }}/docker-artifact/

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load -i docker-artifact/ipa101.tar
            docker stop ipa101 || true
            docker rm -f ipa101 || true
            docker run -d --name ipa101 -p 80:80 ipa101:latest
